services:
  website:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    container_name: my-nginx-container